# set COMMIT SF_USERNAME, SF_PASSWORD and $SF_LOGIN_URL as environment variables

image: node:10.15.0
pipelines:
  branches:
    develop:
      - step:
          name: Show files to Deploy
          script:
            - echo Deploy to UAT
            - git diff HEAD~$COMMIT HEAD --no-renames --name-only
      - step:
          name: Create Package and Deploy
          deployment: test
          caches:
            - node-global
          script:
            - echo Creating salesforce package
            - npm install --global force-dev-tool
            - force-dev-tool remote add test $SF_USERNAME $SF_PASSWORD $SF_LOGIN_URL
            - git diff HEAD~$COMMIT HEAD --no-renames | force-dev-tool changeset create feature-merge -f
            - echo Deploying to salesforce
            - force-dev-tool deploy -t -d config/deployments/feature-merge test
          artifacts:
            - config/deployments/feature-merge

    release:
      - step:
          name: Show files to Deploy
          script:
            - echo Deploy to Staging environment
            - git diff HEAD~$COMMIT HEAD --no-renames --name-only
      - step:
          name: Create Package and Deploy
          deployment: staging
          caches:
            - node-global
          script:
            - echo Creating salesforce package
            - npm install --global force-dev-tool
            - force-dev-tool remote add staging $SF_USERNAME $SF_PASSWORD $SF_LOGIN_URL
            - git diff HEAD~$COMMIT HEAD --no-renames | force-dev-tool changeset create feature-merge -f
            - echo Deploying to salesforce
            - force-dev-tool deploy -t -d config/deployments/feature-merge staging
          artifacts:
            - config/deployments/feature-merge

    master:
      - step:
          name: Show files to Deploy
          script:
            - echo Deploy to Staging environment
            - git diff HEAD~$COMMIT HEAD --no-renames --name-only
      - step:
          name: Create Package and Deploy
          deployment: production
          caches:
            - node-global
          script:
            - echo Creating salesforce package
            - npm install --global force-dev-tool
            - force-dev-tool remote add production $SF_USERNAME $SF_PASSWORD $SF_LOGIN_URL
            - git diff HEAD~$COMMIT HEAD --no-renames | force-dev-tool changeset create feature-merge -f
            - echo Deploying to salesforce
            - force-dev-tool deploy -t -d config/deployments/feature-merge production
          artifacts:
            - config/deployments/feature-merge

definitions:
  caches:
    node-global: /usr/local/lib/node_modules