# set SF_USERNAME, SF_PASSWORD and $SF_LOGIN_URL as environment variables

image: node:10.15.0
pipelines:
  branches:
    develop:
      - step:
          name: Show files to Deploy
          script:
            - echo Deploy to UAT
            - git diff HEAD~1 HEAD --no-renames --name-only
      - step:
          name: Create Package
          caches:
            - node-global
          script:
            - echo Creating salesforce package
            - npm install --global force-dev-tool
            - git diff HEAD~1 HEAD --no-renames | force-dev-tool changeset create feature-merge -f
          artifacts:
            - config/deployments/feature-merge
      - step:
          caches:
            - node-global
          name: Deploy to test
          deployment: test
          #trigger: manual
          script:
            - expr $SF_USERNAME
            - echo Deploy to test
            - npm install --global force-dev-tool
            - force-dev-tool remote add test $SF_USERNAME $SF_PASSWORD $SF_LOGIN_URL
            - force-dev-tool deploy -c -t -d config/deployments/feature-merge test


    release:
      - step:
          name: Show files to Deploy
          script:
            - echo Deploy to Staging environment
            - git diff HEAD~1 HEAD --no-renames --name-only

      - step:
          name: Create Package
          caches:
            - node-global
          script:
            - echo Creating salesforce package
            - npm install --global force-dev-tool
            - git diff HEAD~1 HEAD --no-renames | force-dev-tool changeset create feature-merge -f
          artifacts:
            - config/deployments/feature-merge
      - step:
          caches:
            - node-global
          name: Deploy to staging
          deployment: staging
          #trigger: manual
          script:
            - expr $SF_USERNAME
            - echo Deploy to staging with $SF_USERNAME login
            - npm install --global force-dev-tool
            - force-dev-tool remote add staging $SF_USERNAME $SF_PASSWORD $SF_LOGIN_URL
            - force-dev-tool deploy -c -t -d config/deployments/feature-merge staging


    master:
      - step:
          name: Show files to Deploy
          script:
            - echo Deploy to UAT
            - git diff HEAD~1 HEAD --no-renames --name-only

      - step:
          name: Create Package
          caches:
            - node-global
          script:
            - echo Creating salesforce package
            - npm install --global force-dev-tool
            - git diff HEAD~1 HEAD --no-renames | force-dev-tool changeset create feature-merge -f
          artifacts:
            - config/deployments/feature-merge
      - step:
          caches:
            - node-global
          name: Deploy to test
          deployment: production
          #trigger: manual
          script:
            - expr $SF_USERNAME
            - echo Deploy to production
            - npm install --global force-dev-tool
            - force-dev-tool remote add production $SF_USERNAME $SF_PASSWORD $SF_LOGIN_URL
            - force-dev-tool deploy -c -t -d config/deployments/feature-merge production
definitions:
  caches:
    node-global: /usr/local/lib/node_modules