# set SF_USERNAME, SF_PASSWORD as environment variables

image: node:10.15.0
pipelines:
  branches:
    master:
      - step:
          name: Show files to Deploy
          script:
            - echo Deploy to UAT
            - git diff HEAD~1 HEAD --no-renames --name-only

      - step:
          name: Create Package
          caches:
            - node-global
          script:
            - echo Creating salesforce package
            - npm install --global force-dev-tool
            - git diff HEAD~1 HEAD --no-renames | force-dev-tool changeset create feature-merge -f
          artifacts:
            - config/deployments/feature-merge
      - step:
          caches:
            - node-global
          name: Deploy to test
          deployment: production
          #trigger: manual
          script:
            - echo Deploy to production
            - npm install --global force-dev-tool
            - force-dev-tool remote add production $SF_USERNAME $SF_PASSWORD
            - force-dev-tool deploy -c -t -d config/deployments/feature-merge production

    release:
      - step:
          name: Show files to Deploy
          script:
            - echo Deploy to UAT
            - git diff HEAD~1 HEAD --no-renames --name-only

      - step:
          name: Create Package
          caches:
            - node-global
          script:
            - echo Creating salesforce package
            - npm install --global force-dev-tool
            - git diff HEAD~1 HEAD --no-renames | force-dev-tool changeset create feature-merge -f
          artifacts:
            - config/deployments/feature-merge
      - step:
          caches:
            - node-global
          name: Deploy to staging
          deployment: staging
          #trigger: manual
          script:
            - echo Deploy to staging
            - npm install --global force-dev-tool
            - force-dev-tool remote add staging $SF_USERNAME $SF_PASSWORD
            - force-dev-tool deploy -c -t -d config/deployments/feature-merge staging

    develop:
      - step:
          name: Show files to Deploy
          script:
            - echo Deploy to UAT
            - git diff HEAD~1 HEAD --no-renames --name-only

      - step:
          name: Create Package
          caches:
            - node-global
          script:
            - echo Creating salesforce package
            - npm install --global force-dev-tool
            - git diff HEAD~1 HEAD --no-renames | force-dev-tool changeset create feature-merge -f
          artifacts:
            - config/deployments/feature-merge
      - step:
          caches:
            - node-global
          name: Deploy to test
          deployment: test
          #trigger: manual
          script:
            - echo Deploy to test
            - npm install --global force-dev-tool
            - force-dev-tool remote add test $SF_USERNAME $SF_PASSWORD
            - force-dev-tool deploy -c -t -d config/deployments/feature-merge test

definitions:
  caches:
    node-global: /usr/local/lib/node_modules